apiVersion: apps/v1
kind: Deployment
metadata:
  name: tghelperbot-depl
  labels:
    app: tghelperbot
  namespace: tghelperbot
spec:
  replicas: 1
  revisionHistoryLimit: 0
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: tghelperbot
  template:
    metadata:
      labels:
        app: tghelperbot
    spec:
      containers:
      - name: tghelperbot
        image: "registry.gitlab.com/ahmetzyanov/tghelperbot:BUILD_ID"
        livenessProbe:
          exec:
            command:
              - echo
              - healthy
          initialDelaySeconds: 10
          periodSeconds: 5
      imagePullSecrets:
      - name: gitlab-cred
